import { useEffect, useState } from "react";
import { motion } from "motion/react";
import { Building2, Check, Circle, RefreshCw } from "lucide-react";
import { useServerFn } from "@tanstack/react-start";
import {
  matchInstitutions,
  type InstitutionMatch,
  type InstitutionMatchResult,
} from "@/lib/institution-matching.functions";
import { cn } from "@/lib/utils";
import { useLanguage } from "@/lib/i18n";

/**
 * Level 1 of CivicX matching: which institutions are best suited to this
 * mission. Percentages are calculated deterministically from capability data
 * stored on real university profiles — never generated by the model, and only
 * institutions that have recorded capabilities appear here.
 */
export function InstitutionMatches({
  challengeId,
  ownProfileId,
}: {
  challengeId: string;
  ownProfileId: string | null;
}) {
  const { language } = useLanguage();
  const run = useServerFn(matchInstitutions);
  const [result, setResult] = useState<InstitutionMatchResult | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const load = () => {
    setLoading(true);
    setError(null);
    void (async () => {
      try {
        setResult(await run({ data: { challengeId, language } }));
      } catch (err) {
        console.error("[civicx] institution matching failed", err);
        setError("Institution matching is unavailable right now. You can retry.");
      } finally {
        setLoading(false);
      }
    })();
  };

  useEffect(() => {
    let cancelled = false;
    setResult(null);
    setError(null);
    setLoading(true);
    void (async () => {
      try {
        const data = await run({ data: { challengeId, language } });
        if (!cancelled) setResult(data);
      } catch (err) {
        console.error("[civicx] institution matching failed", err);
        if (!cancelled)
          setError("Institution matching is unavailable right now. You can retry.");
      } finally {
        if (!cancelled) setLoading(false);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [challengeId, run]);

  const own = result?.ownMatch ?? null;
  const ranked = result?.matches ?? [];

  return (
    <div className="glass-soft mt-3 rounded-xl p-4">
      <div className="flex flex-wrap items-center justify-between gap-3">
        <p className="mono-label text-muted-foreground">TOP INSTITUTION MATCHES</p>
        {!loading && (
          <button
            type="button"
            onClick={load}
            className="inline-flex items-center gap-1.5 rounded-lg border border-border px-2.5 py-1 font-mono text-[10px] tracking-[0.14em] text-muted-foreground transition-colors hover:text-foreground"
          >
            <RefreshCw className="h-3 w-3" />
            RECALCULATE
          </button>
        )}
      </div>

      {loading && (
        <p className="mono-label mt-3 text-azure/90">MATCHING INSTITUTIONAL CAPABILITY…</p>
      )}
      {error && <p className="mt-3 text-sm text-destructive">{error}</p>}

      {result && result.requirements.primaryDomain && (
        <p className="mt-3 font-mono text-[10px] tracking-[0.14em] text-cyan">
          REQUIRED DOMAIN: {result.requirements.primaryDomain.toUpperCase()}
        </p>
      )}

      {own && (
        <div className="mt-3 rounded-xl border border-violet/30 bg-violet/5 p-3.5">
          <p className="mono-label text-violet">YOUR INSTITUTION MATCH</p>
          <p className="mt-2 text-sm font-semibold">
            {own.institutionName} —{" "}
            <span className="text-violet">
              {own.percent === null ? "INSUFFICIENT PROFILE DATA" : `${own.percent}% MATCH`}
            </span>
          </p>
          {own.why && (
            <p className="mt-2 text-xs leading-relaxed text-muted-foreground">{own.why}</p>
          )}
        </div>
      )}

      {result && ranked.length === 0 && !error && (
        <p className="mt-3 text-sm text-muted-foreground">
          No institution has recorded capability data yet. Add your academic disciplines,
          research areas, labs and technologies in your profile so CivicX can match your
          institution to missions.
        </p>
      )}

      {ranked.length > 0 && (
        <div className="mt-3 space-y-3">
          {ranked.slice(0, 5).map((match, index) => (
            <MatchCard
              key={match.profileId}
              match={match}
              top={index === 0}
              isOwn={match.profileId === ownProfileId}
            />
          ))}
        </div>
      )}

      {result && !result.aiRequirements && ranked.length > 0 && (
        <p className="mt-3 font-mono text-[10px] tracking-[0.14em] text-muted-foreground">
          MATCHED FROM STORED MISSION DATA — AI REQUIREMENT EXTRACTION UNAVAILABLE
        </p>
      )}
    </div>
  );
}

function MatchCard({
  match,
  top,
  isOwn,
}: {
  match: InstitutionMatch;
  top: boolean;
  isOwn: boolean;
}) {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.35, ease: [0.16, 1, 0.3, 1] }}
      className={cn(
        "rounded-xl border p-3.5",
        top ? "border-cyan/40 bg-cyan/5" : "border-border bg-background/40",
      )}
    >
      <div className="flex flex-wrap items-start justify-between gap-2">
        <div className="min-w-0">
          {top && <p className="mono-label text-cyan">TOP MATCH</p>}
          <p className="mt-1 flex items-center gap-2 text-sm font-semibold">
            <Building2 className="h-3.5 w-3.5 shrink-0 text-azure" />
            <span className="truncate">{match.institutionName}</span>
            {isOwn && (
              <span className="rounded-md border border-violet/40 bg-violet/10 px-1.5 py-0.5 font-mono text-[9px] tracking-[0.14em] text-violet">
                YOU
              </span>
            )}
          </p>
        </div>
        <p className={cn("text-lg font-semibold", top ? "text-cyan" : "text-azure")}>
          {match.percent === null ? "—" : `${match.percent}%`}
          <span className="ml-1 font-mono text-[10px] tracking-[0.14em] text-muted-foreground">
            MATCH
          </span>
        </p>
      </div>

      {match.primaryDomains.length > 0 && (
        <p className="mt-1.5 font-mono text-[10px] tracking-[0.14em] text-muted-foreground">
          {match.primaryDomains.join(" • ").toUpperCase()}
        </p>
      )}

      {match.matchedCapabilities.length > 0 && (
        <ul className="mt-2.5 space-y-1">
          {match.matchedCapabilities.slice(0, 6).map((c) => (
            <li key={c} className="flex items-center gap-2 text-xs text-foreground/85">
              <Check className="h-3 w-3 shrink-0 text-signal" />
              {c}
            </li>
          ))}
        </ul>
      )}

      {match.missingCapabilities.length > 0 && (
        <>
          <p className="mono-label mt-2.5 text-muted-foreground">MISSING</p>
          <ul className="mt-1 space-y-1">
            {match.missingCapabilities.slice(0, 4).map((c) => (
              <li key={c} className="flex items-center gap-2 text-xs text-muted-foreground">
                <Circle className="h-2.5 w-2.5 shrink-0" />
                {c}
              </li>
            ))}
          </ul>
        </>
      )}

      {match.why && (
        <>
          <p className="mono-label mt-2.5 text-muted-foreground">WHY THIS MATCH</p>
          <p className="mt-1 text-xs leading-relaxed text-foreground/85">“{match.why}”</p>
        </>
      )}

      {(match.researchAreas.length > 0 || match.facilities.length > 0) && (
        <p className="mt-2.5 font-mono text-[10px] leading-relaxed tracking-[0.12em] text-muted-foreground">
          {[...match.researchAreas, ...match.facilities].slice(0, 5).join(" · ").toUpperCase()}
        </p>
      )}
    </motion.div>
  );
}
